apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: check-image-policy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucas-92/project-repo.git
    path: helm/kyverno
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

