apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc # A URL do servidor Kubernetes
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.6.0
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      selfHeal: true # Habilita a auto-correção em caso de desvios
    syncOptions:
    - CreateNamespace=true # Cria o namespace se ele não existir
